version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: demo-mosquitto
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSocket
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
